# Generated by Django 5.1.2 on 2024-11-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rental.basemodel')),
                ('no_of_bedrooms', models.IntegerField(blank=True, null=True)),
                ('no_of_bathrooms', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('property_zillow_link', models.URLField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('property_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Error', 'Error')], default='Pending', max_length=20)),
                ('yearly_projected_revenue', models.IntegerField(blank=True, null=True)),
                ('monthly_estimated_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('batch_id', models.IntegerField()),
            ],
            bases=('rental.basemodel',),
        ),
    ]
